language: julia
julia:
  - 0.6
  - nightly
notifications:
    email: false
sudo: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.test("Coverage"; coverage=true)'
  - julia -e 'using Coverage; Coveralls.submit(process_folder())'
  - julia -e 'using Coverage; Codecov.submit(process_folder())'
after_success:
  - if [ "$TRAVIS_JULIA_VERSION" != "nightly" ]; then
      julia -e 'Pkg.rm("Coverage"); Pkg.add("Coverage")';
      julia -e 'using Coverage; Coveralls.submit(process_folder())';
      julia -e 'using Coverage; Codecov.submit(process_folder())';
    fi
