language: julia
julia:
  - 0.6
  - nightly
notifications:
    email: false
sudo: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.test("Coverage"; coverage=true)'
  - julia -e 'using Coverage; cov_res = process_folder(joinpath(Pkg.dir("Coverage"), "src")); Coveralls.submit(cov_res); Codecov.submit(cov_res)';
after_success:
  - if [ "$TRAVIS_JULIA_VERSION" != "nightly" ]; then
      julia -e 'using Coverage; cov_res = process_folder(joinpath(Pkg.dir("Coverage"), "src")); Coveralls.submit(cov_res); Codecov.submit(cov_res)';
    fi
