branches:
  only:
  - master
  - staging
  - trying
  - /^release\/.*$/ # release branches
  - /^v[0-9]+\.[0-9]+\.[0-9]+$/ # version tags

language: julia

os:
  - linux
  - osx
  - windows

arch:
  - x64
  - x86

julia:
  - "1.0"
  - "1.1"
  - "1.2"
  - "1.3"
  - "1"   # Latest stable release, currently "1.4". Add "1.4" into the matrix when it is no longer the latest.
  - nightly

jobs:
  fast_finish: true

  # Test 32-bit only on Linux
  exclude:
    - arch: x86
      os: osx
    - arch: x86
      os: windows

notifications:
  webhooks: https://coveralls.io/webhook
  email: false

script:
  - julia --check-bounds=yes etc/travis-test.jl
  - export COVERALLS_PARALLEL=true
  # submit coverage data, and collect new coverage data on that
  - julia --code-coverage=user etc/travis-coverage.jl
  # submit coverage data *again*, this time without code coverage
  - julia etc/travis-coverage.jl
