language: julia
julia:
  - 0.6
  - 0.7
  - 1.0
  - nightly

notifications:
    email: false

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes etc/travis-test.jl
  # submit coverage data, and collect new coverage data on that
  - julia --code-coverage=user etc/travis-coverage.jl
  # submit coverage data *again*, this time without code coverage
  - julia etc/travis-coverage.jl
