language: julia

os:
  - linux
  - osx

julia:
  - "1.0"
  - "1.1"
  - "1.2"
  - "1.3"
  - nightly
  
env:
  global:
    - COVERALLS_PARALLEL=true

notifications:
  webhooks: https://coveralls.io/webhook
  email: false

script:
  - julia --check-bounds=yes etc/travis-test.jl
  # submit coverage data, and collect new coverage data on that
  - julia --code-coverage=user etc/travis-coverage.jl
  # submit coverage data *again*, this time without code coverage
  - julia etc/travis-coverage.jl
